export const deckManifest = [
  'profile-statement',
  'section-index-01',
  'belief-statement',
  'winning-statement',
  'poster-profile',
  'section-index-02',
  'case-study-02b',
  'case-study-02c',
  'case-study-02d',
  'case-study-02e',
  'case-study-02f',
  'case-study-02h',
  'case-study-02i',
  'case-study-02g',
  'section-index-03',
  'section-index-04',
  'contribution-story',
  'gsap-split',
  'gsap-morph',
  'pattern-offset',
  'pattern-ledger',
  'pattern-stage',
  'pattern-essay',
  'pattern-metric',
  'pattern-poster',
] as const
